### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nishant2019** [kinsi55/node_dvripclient#3]
When I run file to get the video , this error comes up

Receiving 10 seconds of footage...
/home/user/Desktop/projects/cam/node_dvripclient/lib/dvripclient.js:421
		this.setSessionId();
		     ^

TypeError: this.setSessionId is not a function
    at Immediate.disconnect (/home/user/Desktop/projects/cam/node_dvripclient/lib/dvripclient.js:421:8)
    at Immediate.disconnect [as _onImmediate] (/home/user/Desktop/projects/cam/node_dvripclient/lib/dvripstreamclient.js:41:9)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

Also can I redirect video to get live stream

**Comment by kinsi55** [comment]
Can you try editing line 551 from `setImmediate(toDisco.disconnect);` to `setImmediate(toDisco.disconnect.bind(this));` in dvripclient.js ?

Also, yes you can. Both the audio / video returned are streams.

**Comment by nishant2019** [comment]
> video returned are streams.
Thanks , the error is now addressed.
Can guide how I can play the live stream?
Which js lib I should use ?

**Comment by kinsi55** [comment]
I dont know how you could accomplish that as I've never done it. If you just want to view it on the same system the easiest thing you can do is pipe the video stream to ffplay stdin and have ffplay read from stdin, this way you wont get sound tho.

**Comment by kinsi55** [comment]
@nishant2019 In the new Update I've added an example for retreiving the stream in a standardized fashion, maybe thats of use for you.
