### ISSUE TITLE
getVideoStream File format?

### ISSUE THREAD

**Issue by SupertigerDev** [kinsi55/node_dvripclient#4]
What kind of file format does getVideoStream output? I want to use this lib with react native and stream the video on the screen

**Comment by SupertigerDev** [comment]
Nervermind, this package does not work in react native at all :(

**Comment by kinsi55** [comment]
The output of that depends on the DVR / Camera settings. In my tests it was a raw h264 / h265 stream but there probably is other cases where its another format as can be seen in this example https://github.com/kinsi55/node_dvripclient/blob/master/examples/10_sec_mp4.js

Why does it not work with react native?

**Comment by SupertigerDev** [comment]
I see. Thanks. I get errors like stream module not found and crypto not found. I tried installing them, they gave a different error :( I forgot to take note of the error and scrapped the project unfortunately
