### ISSUE TITLE
Question about RTSP quality in VLC 

### ISSUE THREAD

**Issue by SupertigerDev** [kinsi55/node_dvripclient#5]
When using xmeye app on android or vms app on desktop, the quality is good. However when using a link like this `rtsp://192.168.1.142:554/user=admin_password=_channel=1_stream=0.sdp` in VLC Media, the quality is much worse and image glitches out/gets stuck. Is there anyway to fix this?

**Comment by kinsi55** [comment]
I dont see how this is related to my project, anyways: Have you checked the encoding settings in the camera?

>Is there anyway to fix this?

Yes, by using something like this project in conjunction with the Relay example: https://github.com/kinsi55/node_dvripclient/blob/master/examples/relay_stream.js

The RTSP stream most these cameras provide is forced UDP. For anything but a hardwired connection, that will cause issues. The stream parsed and relayed with my method uses TCP and thus is reliable.

**Comment by SupertigerDev** [comment]
Hello, I'm sorry for creating an unrelated issue, I couldn't find a different way to contact you :(
I tried running the example right now and I get this error:
```
# node .\index.js
Connected!
Logged in!
Failed: TypeError: Cannot read properties of undefined (reading 'Video')
    at D:\Fishie\Desktop\test2\index.js:29:36
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

EDIT: nevermind, i need to change it to this `encParams.data[0].MainFormat.Video.FPS`

**Comment by SupertigerDev** [comment]
I'm getting this in the console.
![image](https://user-images.githubusercontent.com/8193841/190644176-c328e0ac-0154-42ca-96bc-31f2d6a9b9f1.png)
I get this error in VLC Media: `VLC is unable to open the MRL 'rtsp://127.0.0.1:554/192.168.1.142'. Check the log for details.`
I currently cant get to the box to check the encoding settings at the moment

**Comment by kinsi55** [comment]
You are running something to ingest into as mentioned in the comment at the top right?

**Comment by SupertigerDev** [comment]
I dont understand what that means. I just want to get my stream be clear when I use VLC :( like VMS or xmeye app

**Comment by kinsi55** [comment]
This example code gets the stream from the camera and then ingests (pushes it into) something - An example being ZLMediaKit. You can then retrieve the stream from it.

You could change the ffmpeg arguments so that instead of publishing it via RTSP, it just makes it available as a raw UDP Stream (Consult Google on how thats accomplished)

**Comment by SupertigerDev** [comment]
![image](https://user-images.githubusercontent.com/8193841/190658377-ab085480-ee56-440f-8c78-dd68eb06d642.png)

Honestly Idk what i'm doing. I tried doing this but its not streaming anything :(

**Comment by kinsi55** [comment]
Does the other example where it writes it directly to a file work?

**Comment by SupertigerDev** [comment]
Yes, the 10 second example works fine, really good quality. I think i'm just not very experienced with ffmpeg

**Comment by SupertigerDev** [comment]
My end goal is to stream in a format such as webm or mp4 or whatever so I can easily stream my camera to chromecast. I want to make a server in between the chrome cast and the dvr and i want the server to stream in a suitable format such as webm or something.

**Comment by kinsi55** [comment]
In that case you'll want to use something like the mentioned zlmediakit

**Comment by SupertigerDev** [comment]
Thanks, I'll take a look but I probably wont get far :(

**Comment by SupertigerDev** [comment]
I managed to re-stream using an ffmpeg server. Its still buggy. I think its an issue with VLC. 
![image](https://user-images.githubusercontent.com/8193841/190673934-87bbd350-88c0-4bc6-ada7-78a204aafd39.png)
Idk how to change the framerate to 15. VLC always defaults to 29fps

**Comment by kinsi55** [comment]
You could try to use ffplay instead

**Comment by SupertigerDev** [comment]
I could but I want to use VLC on my phone because it has a cast button hmm.

**Comment by kinsi55** [comment]
The cameras are of course not fixed framerate but varying due to exposure changes etc, not sure if VLC can properly handle that on a stream, you'll have to figure that out :D

**Comment by SupertigerDev** [comment]
Hm I'm sure there would be a way to make ffmpeg to output as 29fps to the server but allow variable aswell. Just like how you can screen record a 15fps video from 60fps screen recording like obs. Hmm.
